### ISSUE TITLE
22936 질문드립니다!

### ISSUE THREAD

**Issue by LYHyoung** [kth990303/Baekjoon#2]
안녕하세요 백준 22936번 ( https://www.acmicpc.net/problem/22936 )을 풀다 도저히 모르겠어서 코드 
( https://github.com/kth990303/Baekjoon/blob/master/22936_prefix_sum.cpp )를 참고하게 되었습니다

혹시 pp와 p가 무엇을 나타내는지 알고자 issue 남깁니다 :)

**Comment by kth990303** [comment]
안녕하세요.
p와 pp는 테이프의 면적을 누적합으로 구하기 위해 사용됐습니다.
p는 각 날짜에 대한 면적의 누적합이며,
pp는 p의 변화량을 나타낸 것입니다. p의 변화량 pp를 구해주었기 때문에 p를 구할 수 있는 것입니다.

도움이 될만한 문제는 https://www.acmicpc.net/problem/19951 가 있습니다 :)
열공하세요!


> 안녕하세요 백준 22936번 ( https://www.acmicpc.net/problem/22936 )을 풀다 도저히 모르겠어서 코드
> ( https://github.com/kth990303/Baekjoon/blob/master/22936_prefix_sum.cpp )를 참고하게 되었습니다
> 
> 혹시 pp와 p가 무엇을 나타내는지 알고자 issue 남깁니다 :)

**Comment by LYHyoung** [comment]
답변 감사합니다 :)
